# Generated by Django 2.1.5 on 2025-02-13 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_category_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
    ]
